Repository k-morozov/AppChat, pull requests merged in 2020-07, with the labels that each got.

#20 load hostory from storage
  CMakeLists.txt
  src/client/client.cpp
  src/database/database.cpp
  src/database/database.h
  src/protocol/response/transport_response.h
  src/server/channel/channel.cpp
  src/server/channel/channel.h
  src/server/connection/connection.cpp
  src/server/connection/connection.h
  src/storage/database.cpp
  src/storage/database.h
Labels: enhancement

#23 add history for each channel
  src/server/channel/channel.h
  src/storage/database.cpp
  src/storage/database.h
Labels: enhancement

#26 add logins-table
  src/server/connection/connection.cpp
  src/server/connection/connection.h
  src/storage/database.cpp
  src/storage/database.h
Labels: enhancement, good first issue

#28 start work on gui
  CMakeLists.txt
  src/client/client.cpp
  src/client/client.h
  src/client/control.cpp
  src/client/control.h
  src/client/startup_client.cpp
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/mainwindow.ui
Labels: bug, enhancement, help wanted, invalid, question

#31 fix bug with room_id!=1
  src/client/client.cpp
  src/client/client.h
  src/client/control.cpp
  src/client/control.h
  src/protocol/command_table.h
Labels: bug

#35 Change logic autorisation and registration
  src/client/client.cpp
  src/client/client.h
  src/client/control.cpp
  src/client/control.h
  src/client/startup_client.cpp
  src/gui/mainwindow.cpp
  src/gui/mainwindow.h
  src/gui/mainwindow.ui
  src/protocol/command_table.h
  src/protocol/request/input_request.h
  src/protocol/response/input_response.h
  src/server/connection/connection.cpp
  src/server/connection/connection.h
  src/storage/database.cpp
  src/storage/database.h
Labels: enhancement, good first issue

#41 Split cmake
  CMakeLists.txt
  lib/log/CMakeLists.txt
  lib/protocol/CMakeLists.txt
  lib/server/CMakeLists.txt
  lib/server/channel/channel.cpp
  lib/server/channel/channel.h
  lib/server/channel/channels_manager.cpp
  lib/server/channel/channels_manager.h
  lib/server/channel/iroom.cpp
  lib/server/channel/iroom.h
  lib/server/connection/connection.cpp
  lib/server/connection/connection.h
  lib/server/connection/isubscriber.cpp
  lib/server/connection/isubscriber.h
  lib/server/server.h
  lib/server/storage/database.cpp
  lib/server/storage/database.h
  lib/storage/CMakeLists.txt
  lib/storage/database.cpp
  lib/storage/database.h
  src/server/channel/iroom.cpp
  src/server/startup_server.cpp
Labels: enhancement

#42 add cmake for server and client
  CMakeLists.txt
  lib/server/storage/database.cpp
  lib/server/storage/database.h
  src/client/CMakeLists.txt
  src/client/client/client.cpp
  src/client/client/client.h
  src/client/control/control.cpp
  src/client/control/control.h
  src/client/gui/mainwindow.cpp
  src/client/gui/mainwindow.h
  src/client/gui/mainwindow.ui
  src/client/startup_client.cpp
  src/server/CMakeLists.txt
  src/server/channel/channel.cpp
  src/server/channel/channel.h
  src/server/channel/channels_manager.cpp
  src/server/channel/channels_manager.h
  src/server/channel/iroom.cpp
  src/server/channel/iroom.h
  src/server/connection/connection.cpp
  src/server/connection/connection.h
  src/server/connection/isubscriber.cpp
  src/server/connection/isubscriber.h
  src/server/server.h
  src/server/startup_server.cpp
Labels: enhancement

#48 add uml-diagram
  doc/AppChat.dia
  doc/AppChat.png
Labels: documentation, good first issue

#47 add uml
  doc/AppChat.dia
  doc/AppChat.png
Labels: documentation, good first issue

#45 Add more logs
  build_env/install_env.sh
  lib/log/logger.cpp
  lib/log/logger.h
  lib/storage/CMakeLists.txt
  lib/storage/database.cpp
  lib/storage/database.h
  src/client/client/client.cpp
  src/server/channel/channel.cpp
  src/server/channel/channel.h
  src/server/channel/channels_manager.cpp
  src/server/channel/channels_manager.h
  src/server/connection/connection.cpp
  src/server/connection/connection.h
  src/server/startup_server.cpp
Labels: enhancement

#52 Feature add documentation
  .gitignore
  CMakeLists.txt
  Doxyfile
  lib/protocol/response/input_response.h
  src/client/client/client.h
  src/client/control/control.h
  src/client/gui/mainwindow.h
  src/server/channel/channel.h
  src/server/channel/channels_manager.h
  src/server/channel/iroom.h
  src/server/connection/connection.h
  src/server/connection/isubscriber.h
  src/server/server.h
Labels: documentation

#54 Refactoring database
  lib/storage/database.cpp
  lib/storage/database.h
  src/server/channel/channel.h
  src/server/channel/channels_manager.cpp
  src/server/channel/channels_manager.h
  src/server/connection/connection.cpp
  src/server/connection/connection.h
  src/server/server.h
Labels: enhancement

#55 Datetime of messages
  CMakeLists.txt
  lib/protocol/CMakeLists.txt
  lib/protocol/command_table.h
  lib/protocol/datetime.cpp
  lib/protocol/datetime.h
  lib/protocol/request/request.h
  lib/protocol/response/response.h
  lib/protocol/response/transport_response.h
  lib/storage/database.cpp
  src/client/client/client.cpp
  src/client/client/client.h
  src/client/control/control.cpp
  src/client/control/control.h
  src/client/gui/mainwindow.cpp
  src/client/gui/mainwindow.h
  src/server/channel/channel.cpp
  src/server/connection/connection.cpp
  src/tests/test_datetime.cpp
Labels: enhancement
